#!/usr/bin/env python3
"""
EGMS Sub-cluster script  (auto-generated by egms_pipeline_gui.py)
==================================================================
Runs DBSCAN within each parent cluster, stratified by TS class.
Sub-cluster IDs follow the pattern  CL_nnnn_SUB_mm  where CL_nnnn
is the parent cluster ID.

Requirements: pandas, numpy, geopandas, pyarrow, duckdb, scikit-learn,
              scipy, shapely
"""
import argparse
import os
import sys
import time
import warnings
from pathlib import Path

import duckdb
import geopandas as gpd
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from scipy.spatial import ConvexHull
from shapely.geometry import MultiPoint, Point, Polygon, LineString
from sklearn.cluster import DBSCAN

warnings.filterwarnings("ignore")

SEP  = "=" * 68
SEP2 = "-" * 68


def _convex_hull_polygon(east, north):
    pts = np.column_stack([east, north])
    n = len(pts)
    if n == 0: return None
    if n == 1: return Point(pts[0]).buffer(1)
    if n == 2: return LineString(pts).buffer(1)
    try:
        hull = ConvexHull(pts)
        return Polygon(pts[hull.vertices])
    except Exception:
        return MultiPoint(pts).convex_hull


def main():
    parser = argparse.ArgumentParser(description="EGMS sub-cluster by parent + TS class")
    parser.add_argument("--data-dir",       required=True)
    parser.add_argument("--eps-m",          type=float, default=50.0)
    parser.add_argument("--eps-vel",        type=float, default=2.0)
    parser.add_argument("--min-samples",    type=int,   default=3)
    parser.add_argument("--buffer-m",       type=float, default=15.0)
    parser.add_argument("--active-classes", default="linear,accel,decel,variable,jump,other")
    parser.add_argument("--shapefile",      action="store_true",
                        help="Also export sub-cluster polygons as ESRI Shapefile (.shp)")
    parser.add_argument("--n-jobs",         type=int, default=-1,
                        help="Parallel workers for group DBSCAN (-1=all cores, default -1)")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    active   = [c.strip() for c in args.active_classes.split(",") if c.strip()]

    print(f"\n{SEP}")
    print("  EGMS SUB-CLUSTER DETECTOR")
    print(f"{SEP}")
    print(f"  data_dir       : {data_dir}")
    print(f"  eps_m          : {args.eps_m} m")
    print(f"  eps_vel        : {args.eps_vel} mm/yr")
    print(f"  min_samples    : {args.min_samples}")
    print(f"  buffer_m       : {args.buffer_m} m")
    print(f"  active classes : {active}")
    print(f"  shapefile      : {'YES' if args.shapefile else 'NO'}")

    # ── Explicit file list (avoids glob picking up cluster polygon outputs) ─
    meta_files = sorted(data_dir.rglob("*_meta.parquet"))
    meta_files = [f for f in meta_files
                  if "clusters_" not in f.name
                  and "subcluster" not in f.name]
    if not meta_files:
        print("ERROR: No *_meta.parquet files found.")
        sys.exit(1)

    print(f"  Found {len(meta_files)} meta parquet file(s)", flush=True)

    # Build explicit file list for DuckDB — avoids schema-union issues
    # with any polygon/output parquets left in the same folder
    file_list = "[" + ", ".join(f"'{f.as_posix()}'" for f in meta_files) + "]"

    con = duckdb.connect(":memory:")
    con.execute(f"CREATE VIEW meta AS SELECT * FROM read_parquet({file_list}, union_by_name=True)")

    # Check cluster_id and class_1 exist
    try:
        con.execute("SELECT cluster_id, class_1 FROM meta LIMIT 0")
    except Exception as e:
        print(f"ERROR: {e}")
        print("Run clustering and classification first.")
        sys.exit(1)

    cls_filter = "', '".join(active)
    print(f"  Querying eligible points ...", flush=True)
    df = con.execute(f"""
        SELECT CAST(pid AS VARCHAR) AS pid,
               CAST(easting AS DOUBLE) AS easting,
               CAST(northing AS DOUBLE) AS northing,
               CAST(mean_velocity AS DOUBLE) AS mean_velocity,
               CAST(cluster_id AS VARCHAR) AS cluster_id,
               CAST(class_1 AS VARCHAR) AS class_1
        FROM meta
        WHERE cluster_id IS NOT NULL
          AND cluster_id != 'NOISE'
          AND class_1 IN ('{cls_filter}')
    """).df()
    con.close()

    print(f"  Eligible points: {len(df):,}")
    if df.empty:
        print("  No eligible points — check cluster_id and class_1 columns.")
        sys.exit(1)

    t0 = time.time()

    df = df.reset_index(drop=True)

    # ── Pre-sort by cluster_id+class_1, then use itertools.groupby ────────
    # Avoids pandas GroupBy object overhead entirely. Sort once on integer
    # codes (fast), then iterate with pure Python groupby on the sorted array.
    print(f"  Sorting and grouping ...", flush=True)
    df["_cid_cls"] = df["cluster_id"] + "|" + df["class_1"]
    sort_idx = df["_cid_cls"].argsort().values   # numpy argsort on strings
    df_s = df.iloc[sort_idx].reset_index(drop=True)

    keys    = df_s["_cid_cls"].values
    cids    = df_s["cluster_id"].values
    clss    = df_s["class_1"].values
    easts   = df_s["easting"].values
    norths  = df_s["northing"].values
    vels    = df_s["mean_velocity"].values

    # Find group boundaries using numpy (no pandas overhead)
    change  = np.concatenate(([True], keys[1:] != keys[:-1], [True]))
    starts  = np.where(change)[0]
    n_groups = len(starts) - 1
    print(f"  Parent×Class groups: {n_groups:,}", flush=True)

    vel_w    = args.eps_m / max(args.eps_vel, 0.01)
    eps_m    = args.eps_m
    eps_vel  = args.eps_vel
    min_samp = args.min_samples
    buf_m    = args.buffer_m

    # ── Module-level worker function for parallel execution ───────────────
    # Defined at module level in the GUI-generated script to allow pickling.
    # Here we define it as a closure-free standalone and pass all data as args.

    def _run_group(s, e, cid, cls, east, north, vel,
                   eps_m, min_samples, vel_w, buffer_m):
        n = e - s
        if n < min_samples:
            return s, e, np.full(n, f"{cid}_SUB_NOISE", dtype=object), []
        X      = np.column_stack([east, north, vel * vel_w])
        labels = DBSCAN(eps=eps_m, min_samples=min_samples,
                        algorithm="ball_tree", metric="euclidean",
                        n_jobs=1).fit_predict(X)
        lbl_to_subid = {}
        poly_rows_out = []
        for lbl in np.unique(labels):
            if lbl == -1:
                lbl_to_subid[lbl] = f"{cid}_SUB_NOISE"
            else:
                sub_id = f"{cid}_SUB_{lbl:03d}"
                lbl_to_subid[lbl] = sub_id
                mask = labels == lbl
                poly = _convex_hull_polygon(east[mask], north[mask])
                if poly is not None:
                    poly_rows_out.append({
                        "subcluster_id": sub_id,
                        "parent_id":     cid,
                        "ts_class":      cls,
                        "n_points":      int(mask.sum()),
                        "mean_vel":      float(vel[mask].mean()),
                        "geometry":      poly.buffer(buffer_m),
                    })
        sub_ids = np.array([lbl_to_subid[lbl] for lbl in labels], dtype=object)
        return s, e, sub_ids, poly_rows_out

    # ── Prepare group task list ───────────────────────────────────────────
    group_tasks = []
    for i in range(n_groups):
        s, e = starts[i], starts[i + 1]
        group_tasks.append((
            s, e,
            cids[s], clss[s],
            easts[s:e].copy(),   # copy slice — safe for parallel use
            norths[s:e].copy(),
            vels[s:e].copy(),
            eps_m, min_samp, vel_w, buf_m,
        ))

    # ── Run in parallel ───────────────────────────────────────────────────
    from joblib import Parallel, delayed as _delayed
    n_cores  = os.cpu_count() or 1
    n_jobs   = args.n_jobs
    eff_jobs = n_cores if n_jobs == -1 else min(abs(n_jobs), n_cores)
    print(f"  Running {n_groups:,} group DBSCANs "
          f"({eff_jobs} parallel workers) ...", flush=True)

    subcluster_ids = np.full(len(df_s), "NOISE", dtype=object)
    poly_rows = []
    sub_count = 0
    report_every = max(1, n_groups // 20)

    gen = Parallel(n_jobs=n_jobs, backend="threading",
                   return_as="generator")(
        _delayed(_run_group)(*task) for task in group_tasks
    )

    for done, (s, e, sub_ids, poly_rows_out) in enumerate(gen, 1):
        subcluster_ids[s:e] = sub_ids
        poly_rows.extend(poly_rows_out)
        sub_count += len(poly_rows_out)
        if done % report_every == 0 or done == n_groups:
            elapsed = time.time() - t0
            rate    = done / elapsed if elapsed > 0 else 0
            eta     = (n_groups - done) / rate if rate > 0 else 0
            print(f"  [{done:>6}/{n_groups}]  {sub_count:,} sub-clusters  "
                  f"| {elapsed:.0f}s elapsed  ETA {eta:.0f}s", flush=True)

    # Map subcluster_ids back to original df order via sort_idx
    result = np.full(len(df), "NOISE", dtype=object)
    result[sort_idx] = subcluster_ids
    df["subcluster_id"] = result

    elapsed = time.time() - t0
    print(f"  Sub-clusters found : {sub_count:,}  (in {elapsed:.1f} s)", flush=True)

    # ── Write subcluster_id back to parquet files (parallel) ────────────
    meta_files = [f for f in data_dir.rglob("*_meta.parquet")
                  if "clusters_" not in f.name and "subcluster" not in f.name]

    sub_map = df[["pid", "subcluster_id"]].drop_duplicates("pid")

    def _write_sub_parquet(mf):
        try:
            tbl      = pq.read_table(mf)
            existing = tbl.to_pandas()
            if "subcluster_id" in existing.columns:
                existing = existing.drop(columns=["subcluster_id"])
            merged = existing.merge(sub_map, on="pid", how="left")
            schema = pa.Schema.from_pandas(merged, preserve_index=False)
            pq.write_table(pa.Table.from_pandas(merged, schema=schema), mf)
            return f"  v Updated {mf.name}"
        except Exception as ex:
            return f"  x {mf.name}: {ex}"

    from joblib import Parallel, delayed as _delayed
    wb_jobs = min(16, os.cpu_count() or 1)
    print(f"  Writing subcluster_id to {len(meta_files)} files "
          f"({wb_jobs} parallel writers) ...", flush=True)
    wb_results = Parallel(n_jobs=wb_jobs, backend="threading")(
        _delayed(_write_sub_parquet)(mf) for mf in meta_files
    )
    for msg in wb_results:
        print(msg, flush=True)

    # Save polygon outputs
    if poly_rows:
        gdf = gpd.GeoDataFrame(poly_rows, crs="EPSG:3035")
        out_gpkg = data_dir / "subclusters_polygons.gpkg"
        gdf.to_file(out_gpkg, driver="GPKG")
        print(f"  ✓ Sub-cluster polygons: {out_gpkg}")
        if args.shapefile:
            out_shp = data_dir / "subclusters_polygons.shp"
            # Truncate column names to 10 chars for DBF format
            shp_gdf = gdf.to_crs(epsg=4326).copy()
            col_map = {}
            seen = set()
            for col in shp_gdf.columns:
                if col == "geometry":
                    continue
                short = col[:10]
                if short in seen:
                    short = col[:8] + f"{sum(1 for s in seen if s.startswith(col[:8])):02d}"
                seen.add(short)
                col_map[col] = short
            shp_gdf = shp_gdf.rename(columns=col_map)
            shp_gdf.to_file(out_shp, driver="ESRI Shapefile")
            print(f"  ✓ Shapefile           : {out_shp}")

    print(f"\n✓ Sub-clustering complete in {time.time()-t0:.1f} s")
    print(f"{SEP}\n")


if __name__ == "__main__":
    main()
